services:
  - type: web
    name: supabase-ota-travel-fastapi
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false # Giá trị thực tế bạn điền thủ công trên Render Dashboard
